menu:
  主页: /
  归档: /archives


rss:

more:
  Github: https://github.com/gaoryrt/
  微博: http://weibo.com/R1T1AN
  知乎: https://www.zhihu.com/people/gaoryrt
  rss: /rss2.xml
  关于我: /CV

parallax_pic_1: http://7xs4ih.com1.z0.glb.clouddn.com/parallax1.jpg
parallax_pic_2: http://7xs4ih.com1.z0.glb.clouddn.com/parallax2.jpg

google-site-verification: xyaFwSI1VZa80BtZHe7okdwZ9tuTs-lYAAuDt1bsCxM
